#!/usr/bin/env bash
set -euo pipefail

SPEC_PATH="${1:-}"

if [ -z "$SPEC_PATH" ]; then
  echo "Usage: $0 <spec.json>"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required"
  exit 1
fi

NODE="$(jq -re '.node' "$SPEC_PATH")"
HOSTNAME="$(jq -re '.hostname' "$SPEC_PATH")"
MGMT_IP_CIDR="$(jq -re '.mgmt_ip_cidr' "$SPEC_PATH")"
BASE_QCOW2="$(jq -re '.base_qcow2' "$SPEC_PATH")"
MAKE_CONFIG_SH="$(jq -re '.make_config_sh' "$SPEC_PATH")"

NODE_DIR="vjunos/${NODE}"
RENDER_DIR="${NODE_DIR}/rendered"
DISK_PATH="${NODE_DIR}/disk.qcow2"
CONFIG_IMG="${NODE_DIR}/config.img"
CONF_PATH="${RENDER_DIR}/juniper.conf"

mkdir -p "$RENDER_DIR"

cat >"$CONF_PATH" <<EOF
## generated by build-node.sh
system {
  host-name ${HOSTNAME};
  services {
    ssh;
  }
}

interfaces {
  fxp0 {
    unit 0 {
      family inet {
        address ${MGMT_IP_CIDR};
      }
    }
  }
}

chassis {
  no-auto-image-upgrade;
}
EOF

rm -f "$DISK_PATH"
qemu-img create -f qcow2 -F qcow2 -b "$BASE_QCOW2" "$DISK_PATH"

rm -f "$CONFIG_IMG"
if "$MAKE_CONFIG_SH" -c "$CONF_PATH" -i "$CONFIG_IMG"; then
  :
elif "$MAKE_CONFIG_SH" -c "$CONF_PATH" -o "$CONFIG_IMG"; then
  :
else
  "$MAKE_CONFIG_SH" "$CONF_PATH" "$CONFIG_IMG"
fi

echo "Generated artifacts:"
echo "- ${DISK_PATH}"
echo "- ${CONFIG_IMG}"
echo "- ${CONF_PATH}"
