#!/usr/bin/env bash
set -euo pipefail

SPEC_PATH="${1:-}"

# This block checks whether an argument has been given (i.e. a json file with parameters) and exits with 1 if not
if [ -z "$SPEC_PATH" ]; then
  echo "Usage: $0 <spec.json>"
  exit 1
fi

# This block checks whether jq (a cli json processor) is installed and exits with 1 if not
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required"
  exit 1
fi

# Input parameters
NODE="$(jq -re '.node' "$SPEC_PATH")"
HOSTNAME="$(jq -re '.hostname' "$SPEC_PATH")"
MGMT_IP_CIDR="$(jq -re '.mgmt_ip_cidr' "$SPEC_PATH")"
PUBKEY="$(jq -re '.pubkey' "$SPEC_PATH")"
BASE_QCOW2="$(jq -re '.base_qcow2' "$SPEC_PATH")"
MAKE_CONFIG_SH="$(jq -re '.make_config_sh' "$SPEC_PATH")"

# Output parameters
NODE_DIR="vjunos/${NODE}"
RENDER_DIR="${NODE_DIR}/rendered"
DISK_PATH="${NODE_DIR}/disk.qcow2"
CONFIG_IMG="${NODE_DIR}/config.img"
CONF_PATH="${RENDER_DIR}/juniper.conf"

mkdir -p "$RENDER_DIR"


# Basic day-0 config (hostname, ssh with certificate, assigning an oobm ip for fxp0, disabling autoimageupgrade)
cat >"$CONF_PATH" <<EOF
## generated by build-node.sh
system {
  host-name ${HOSTNAME};
  services {
    ssh;
  }
  root-authentication {
    ${PUBKEY};
  }
}

interfaces {
  fxp0 {
    unit 0 {
      family inet {
        address ${MGMT_IP_CIDR};
      }
    }
  }
}

chassis {
  no-auto-image-upgrade;
}
EOF

# Deletes the overlay if it was already present so it doesn't conflict
rm -f "$DISK_PATH"

# Creates a qcow2 overlay, with the original qcow2 as its backing file
qemu-img create -f qcow2 -F qcow2 -b "$BASE_QCOW2" "$DISK_PATH"

# Just as above, deletes the older config image if it existed
rm -f "$CONFIG_IMG"

# Uses Juniper-provided make_config.sh to generate a disk image config_img from a config path (points to juniper.conf)
"$MAKE_CONFIG_SH" "$CONF_PATH" "$CONFIG_IMG"

# This is a bash test [[...]], checks if config_img exists and has a size 0> bytes (-s). || runs the right side (exit with 1) if fails 
[[ -s "$CONFIG_IMG" ]] || { echo "ERROR: config.img was not created"; exit 1; }

echo "Generated artifacts:"
echo "- ${DISK_PATH}"
echo "- ${CONFIG_IMG}"
echo "- ${CONF_PATH}"
